// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtnmapsqtrizvnueqjhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0bm1hcHNxdHJpenZudWVxamh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDg5MzEsImV4cCI6MjA2NjUyNDkzMX0.yDU1wIhO3FfZwE_b-0QgUIHv_NEIsjuKuoltjS-ZOd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);